name: CI checks
on: [push]
jobs:

  build:
    name: CI steps
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run the CI steps action
      uses: epavlova/golang-ci-action@master
      with:
        coveralls-token: ${{ secrets.COVERALLS_TOKEN }}
